// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadHelloringbuffer returns the embedded CollectionSpec for Helloringbuffer.
func LoadHelloringbuffer() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_HelloringbufferBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Helloringbuffer: %w", err)
	}

	return spec, err
}

// LoadHelloringbufferObjects loads Helloringbuffer and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*HelloringbufferObjects
//	*HelloringbufferPrograms
//	*HelloringbufferMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadHelloringbufferObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadHelloringbuffer()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// HelloringbufferSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type HelloringbufferSpecs struct {
	HelloringbufferProgramSpecs
	HelloringbufferMapSpecs
	HelloringbufferVariableSpecs
}

// HelloringbufferProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type HelloringbufferProgramSpecs struct {
	HelloRingBuff *ebpf.ProgramSpec `ebpf:"hello_ring_buff"`
}

// HelloringbufferMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type HelloringbufferMapSpecs struct {
	Output *ebpf.MapSpec `ebpf:"output"`
}

// HelloringbufferVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type HelloringbufferVariableSpecs struct {
}

// HelloringbufferObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadHelloringbufferObjects or ebpf.CollectionSpec.LoadAndAssign.
type HelloringbufferObjects struct {
	HelloringbufferPrograms
	HelloringbufferMaps
	HelloringbufferVariables
}

func (o *HelloringbufferObjects) Close() error {
	return _HelloringbufferClose(
		&o.HelloringbufferPrograms,
		&o.HelloringbufferMaps,
	)
}

// HelloringbufferMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadHelloringbufferObjects or ebpf.CollectionSpec.LoadAndAssign.
type HelloringbufferMaps struct {
	Output *ebpf.Map `ebpf:"output"`
}

func (m *HelloringbufferMaps) Close() error {
	return _HelloringbufferClose(
		m.Output,
	)
}

// HelloringbufferVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadHelloringbufferObjects or ebpf.CollectionSpec.LoadAndAssign.
type HelloringbufferVariables struct {
}

// HelloringbufferPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadHelloringbufferObjects or ebpf.CollectionSpec.LoadAndAssign.
type HelloringbufferPrograms struct {
	HelloRingBuff *ebpf.Program `ebpf:"hello_ring_buff"`
}

func (p *HelloringbufferPrograms) Close() error {
	return _HelloringbufferClose(
		p.HelloRingBuff,
	)
}

func _HelloringbufferClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed helloringbuffer_bpfel.o
var _HelloringbufferBytes []byte
